---
- name: Prepare the local container
  hosts: deployer
  roles:
    - role: build-common
      project_paths: ["{{ deployer_local_workspace }}/dev-tutorial-api"]
    - role: build-api
    - role: run-common
    - role: run-api

- name: Prepare the production packaging
  hosts: backend
  roles:
    - role: package-api

- name: Remove temporary objects to prevent conflicts
  hosts: deployer
  gather_facts: no
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Remove temporary container
      docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ api_image }}"
        - "{{ db_image }}"
