---
- name: Verify
  hosts: instance
  gather_facts: no
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Get docker host info
      docker_host_info:
        verbose_output: yes
        containers: yes
        containers_filters:
          status: running
      register: result

    - name: Make sure the application containers are running
      assert:
        that:
          - "('/' + deployer_container_prod_api) in containers"
      vars:
        containers: "{{ result.containers | map(attribute='Names') | flatten }}"

    - name: Wait for frontend ports
      wait_for:
        port: "{{ item }}"
        timeout: 120
        state: started
      loop:
        - 3000
        - 3001
      delegate_to: "{{ deployer_container_prod_api }}"

    - name: Make sure the app is started
      uri:
        url: "http://localhost:3000/api/tuto"
      delegate_to: "{{ deployer_container_prod_api }}"
