---
docsgen_generators:
  - file: generators/asyncapi.yml
  - file: generators/marked.yml
  - file: generators/openapi.yml
  - file: generators/coverage.yml
  - file: generators/typedoc.yml
    task_item: api
  - file: generators/typedoc.yml
    task_item: app
