---
docsgen_generators:
  - name: asyncapi
    dependencies:
      - { name: "@asyncapi/generator" }
      # - { name: "redoc-asyncapi" }

  - name: marked
    dependencies:
      - { name: "marked" }

  - name: openapi
    dependencies:
      - { name: "swagger-jsdoc", version: 6 }
      - { name: "redoc-cli" }

  - name: coverage
    dependencies: []

  - name: zap
    task_item: api-scan
    dependencies: []

  - name: zap
    task_item: full-scan
    dependencies: []

  - name: typedoc
    task_item: api
    dependencies: &id001
      - { name: "typescript" }
      - { name: "typedoc" }

  - name: typedoc
    task_item: app
    dependencies: *id001
