# {{ ansible_managed }}
FROM nginx:1.19
COPY {{ app_package }} /usr/share/nginx/dev-tutorial-app
COPY dev-tutorial-app.conf /etc/nginx/conf.d/default.conf
RUN apt-get update -y && apt-get install python3 -y
