# {{ ansible_managed }}
FROM node:15
ENV NODE_ENV=production
COPY dist/ /usr/src/dev-tutorial-api/dist/
COPY tutorials/ /usr/src/dev-tutorial-api/tutorials/
COPY package.json /usr/src/dev-tutorial-api/
COPY yarn.lock /usr/src/dev-tutorial-api/
COPY openapi-generated.yml /usr/src/dev-tutorial-api/
WORKDIR /usr/src/dev-tutorial-api
RUN yarn install && yarn cache clean
CMD yarn start
