---
- name: Prepare the CI environment
  hosts: all
  roles:
    - role: dockerize
      deployer_env: ci
      dockerize_backend_command: yarn test-ci
      dockerize_frontend_command: yarn test-ci
      dockerize_wait_for_init: no
