---
- name: Prepare the local development environment
  hosts: deployer
  roles:
    - role: dockerize
      deployer_env: dev
      dockerize_backend_command: yarn serve
      dockerize_frontend_command: yarn start --host 0.0.0.0 --no-progress
      dockerize_container_env_backend:
        DEBUG: "server:*,app:access,docker:*"
      dockerize_api_token_access_secret: lagv9f6whb4yd6oiyqxxabb2f4u0prw0
      dockerize_api_token_refresh_secret: zsoxh0mdmygu7q1nt2sls4p7u7t5kq0h
  post_tasks:
    - name: Check for backend initialization
      delegate_to: dev-tutorial-api
      uri:
        url: http://localhost:3000/api/tuto
      register: _result
      until: _result.status == 200
      retries: 10
      delay: 5
      tags: api

    - name: Check for frontend initialization
      delegate_to: dev-tutorial-app
      uri:
        url: "http://localhost:4200"
      register: _result
      until: _result.status == 200
      retries: 15
      delay: 30
      tags: app
