---
- name: Generate the project documentation
  hosts: deployer
  tasks:
    - name: Run the docsgen container
      docker_container:
        name: dev-tutorial-docsgen
        image: node:14
        state: started
        auto_remove: yes
        tty: yes
        working_dir: "/usr/src"
        volumes:
          - "{{ deployer_hosted_workspace }}:/usr/src"
          - "/usr/src/dev-tutorial-api/node_modules"
          - "/usr/src/dev-tutorial-app/node_modules"

- name: Generate the documentation
  hosts: dev-tutorial-docsgen
  roles:
    - role: docsgen

- name: Generate the project documentation
  hosts: deployer
  tasks:
    - name: Stop and remove the container
      docker_container:
        name: dev-tutorial-docsgen
        state: absent
      tags:
        - never
        - clean
