---
- name: Expose the project documentation
  hosts: deployer
  tasks:
    - name: Pull the server image
      docker_image:
        name: nginx
        source: pull

    - name: Manage the docs server
      docker_container:
        name: dev-tutorial-docs
        image: nginx
        state: "{{ docs_state | default('started') }}"
        restart: "{{ docs_restart | default(False) }}"
        auto_remove: yes
        ports:
          - "8000:80"
        volumes:
          - "{{ deployer_hosted_workspace }}/docs/html:/usr/share/nginx/html:ro"
