---
- name: Generate the project documentation
  hosts: deployer
  tags: generate
  pre_tasks:
    - name: Pull a node image
      docker_image:
        name: node:14
        source: pull
      tags: always
    - name: Run a node container
      docker_container:
        name: dev-tutorial-docsgen
        image: node:14
        state: started
        auto_remove: yes
        tty: yes
        working_dir: "/usr/src"
        volumes:
          - "{{ deployer_hosted_workspace }}:/usr/src"
          - "/usr/src/dev-tutorial-api/node_modules"
          - "/usr/src/dev-tutorial-app/node_modules"
      tags: always
    - name: Add container to inventory
      add_host:
        name: dev-tutorial-docsgen
        ansible_connection: docker
        ansible_python_interpreter: /usr/bin/python3
      changed_when: False
      tags: always
  roles:
    - role: docsgen
      delegate_to: dev-tutorial-docsgen
  post_tasks:
    - name: Stop the container
      docker_container:
        name: dev-tutorial-docsgen
        state: absent
      tags:
        - never
        - clean
