---
# Check that applications are running and are reachable
# You can pass the healthcheck_wait variable if you just start the containers
#   to wait until application ports are reachables
- name: Backend applications healthcheck
  hosts: backends
  tags: api
  tasks:
    - name: Wait for backend application ports
      wait_for:
        port: "{{ item }}"
        sleep: 5
        timeout: 60
        state: started
      loop: ["{{ api_port }}", "{{ socket_port }}"]
      when: "healthcheck_wait is defined and healthcheck_wait | bool"

    - name: Backend check
      uri:
        url: "http://localhost:{{ api_port }}/api/tuto"

- name: Frontend applications healthcheck
  hosts: frontends
  tags: app
  tasks:
    - name: Wait for frontend application ports
      wait_for:
        port: "{{ app_port | default(80) }}"
        sleep: 5
        timeout: 600
        state: started
      when: "healthcheck_wait is defined and healthcheck_wait | bool"

    - name: Frontend check
      uri:
        url: "http://localhost:{{ port }}/"
      vars:
        port: "{{ app_port | default(80) }}"
