---
- name: Generate the backend production package
  hosts: dev-tutorial-api
  roles:
    - role: package-api

- name: Generate the frontend production package
  hosts: dev-tutorial-app
  roles:
    - role: package-app
