---
- name: Generate the backend production package
  any_errors_fatal: true
  hosts:
    - deployer
    - dev-tutorial-api
  roles:
    - role: package-api

- name: Generate the frontend production package
  any_errors_fatal: true
  hosts:
    - deployer
    - dev-tutorial-app
  roles:
    - role: package-app
