---
- name: Prepare the local test environment
  hosts: deployer
  roles:
    - role: dockerize
      deployer_env: test
      dockerize_backend_command: yarn test
      dockerize_frontend_command: yarn test --no-progress
      dockerize_container_env_backend:
        CHOMA_SEED: "" # "HDI6Xxc9xc"
        DEBUG: "" # "app:server,app:access,app:docker,test:*,socket.io:*"
        DEV_API_EXTRA_TUTORIALS: "test/extra-tuto test/extra-tuto2"
      dockerize_api_token_access_secret: esd5isvyy12g5sg3lorisb8n389kgktg
      dockerize_api_token_access_expiresIn: 120
      dockerize_api_token_refresh_secret: 49ur5zzpocrqwfvtzjcvp89q7nlnqozf
  post_tasks:
    - name: Check for frontend initialization
      delegate_to: dev-tutorial-app
      uri:
        url: "http://localhost:9876"
      register: _result
      until: _result.status == 200
      retries: 15
      delay: 30
      tags: app
