---
- name: Prepare the local test environment
  hosts: all
  roles:
    - role: dockerize
      deployer_env: test
      dockerize_backend_command: yarn test
      dockerize_frontend_command: yarn test --no-progress
      dockerize_wait_for_init: no
      dockerize_container_env_backend:
        DEBUG: "app:server,app:access,app:docker,test:*"
        DEV_API_EXTRA_TUTORIALS: "test/extra-tuto test/extra-tuto2"
        CHOMA_SEED: "HDI6Xxc9xc"
      dockerize_app_port: 9876
