---
run_app_force: no
run_app_image: dev-tutorial-app
run_app_container: dev-tutorial-app
run_app_production: yes
run_app_port: 4200
run_app_karma_port: 9876
run_app_disable_terminal: no

# API info
run_app_api_host: "http://dev-tutorial-api"
run_api_port: 3000
run_api_socket_port: 3001
