# Configuration file for Mega-Linter
# See all available variables at https://nvuillam.github.io/mega-linter/configuration/ and in linters documentation

# Main
DEFAULT_BRANCH: main
APPLY_FIXES: none
DISABLE:
  - HTML # wait new version (.htmlintrc not functional)
  - SPELL
FLAVOR_SUGGESTIONS: false
PRINT_ALPACA: false

# Reporters
UPDATED_SOURCES_REPORTER: false

# Linter specific
ANSIBLE_DIRECTORY: dev-tutorial-deployer
SPELL_CSPELL_ARGUMENTS: --local "en,fr"
SPELL_MISSPELL_FILTER_REGEX_EXCLUDE: '.*\.fr\..*'
YAML_V8R_FILTER_REGEX_EXCLUDE: '.mega-linter.yml' # https://github.com/nvuillam/mega-linter/issues/321
TYPESCRIPT_ES_RULES_PATH: /tmp/lint/.github/linters
TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.yml
