version: '3'
services:
  api:
    command: yarn test
    environment:
      - DEBUG=app:docker,app:access
#      - CHOMA_SEED=ogWYLufMQK
  app:
    image: dev-tutorial-app-test
    container_name: dev-tutorial-app-test
    build:
      dockerfile: Dockerfile-Test
    command: yarn test
