version: '3'
services:
  api:
    command: ./build.py start --prod
    image: dev-tutorial-api-prod
    build:
      dockerfile: Dockerfile-Prod
    volumes:
      - /usr/src/app/api
  app:
    image: dev-tutorial-app-prod
    container_name: dev-tutorial-app-test
    build:
      dockerfile: Dockerfile-Prod
    volumes:
      - /usr/src/app/app-ui
