---
run_api_image: "{{ deployer_image_api }}"
run_api_container: "{{ deployer_container_api }}"
run_api_db_image: "{{ deployer_image_db }}"
run_api_db_container: "{{ deployer_container_db }}"
run_api_network_db: "{{ deployer_network_db }}"
run_api_network_api: "{{ deployer_network_api }}"
run_api_env: {}
run_api_force: no
run_api_production: yes
run_api_port: 3000
run_api_socket_port: 3001
run_api_mongodb: "mongodb://{{ run_api_db_container }}:27017/dev_tutorial_api"
run_api_token_access_expiresIn: 120
run_api_token_refresh_expiresIn: 604800
