---
- name: Cleanup
  hosts: deployer
  gather_facts: no
  no_log: "{{ molecule_no_log }}"
  tasks:
    - fail:
        msg: "{{ deployer_image_api }}"
    - name: Destroy images
      docker_image:
        name: "{{ deployer_image_api }}"
        state: absent
        force_absent: yes
