---
- name: Converge
  hosts: localhost
  vars:
    deployer_env: molecule
    deployer_host_system: "{{ lookup('env', 'HOST_SYSTEM') }}"
    deployer_local_workspace: "{{ lookup('env', 'WORKSPACE_LOCAL') }}"
    deployer_hosted_workspace: "{{ lookup('env', 'WORKSPACE_HOSTED') }}"
    build_api_image: dev-tutorial-api-molecule
  roles:
    - role: build-common
      project_paths:
        - "{{ deployer_local_workspace }}/dev-tutorial-api"
    - role: build-api
