---
- name: Verify
  hosts: deployer
  no_log: "{{ molecule_no_log }}"
  gather_facts: no
  tasks:
    - name: Get docker host info
      docker_host_info:
        verbose_output: yes
        images: yes
      register: result

    - name: Make sur that images exist
      assert:
        that:
          - "(deployer_image_api + ':latest') in images"
      vars:
        images: "{{ result.images | map(attribute='RepoTags') | flatten }}"
