---
- name: Get the docker host setup if not set (linux)
  set_fact:
    dockerize_api_docker: { socketPath: '/var/run/docker.sock' }
  when: 
    - "dockerize_api_docker is none"
    - "'linux' == deployer_host_system"

- name: Get the docker host setup if not set (non-linux)
  set_fact:
    dockerize_api_docker: { host: 'host.docker.internal', port: 2375 }
  when: 
    - "dockerize_api_docker is none"
    - "'linux' != deployer_host_system"

- name: Generate environment files
  template:
    src: environments/environment.api.ts.j2
    dest: "{{ deployer_local_workspace }}/dev-tutorial-api/src/environments/environment.ts"
  loop:

- name: Generate frontend environment file
  template:
    src: environments/environment.app.ts.j2
    dest: "{{ deployer_local_workspace }}/dev-tutorial-app/src/environments/environment.ts"
