---
- name: Get info on docker host
  docker_host_info:
    containers: yes
    containers_filters:
      status: running
      name: dev-tutorial-*
  register: result
  tags: always

- name: Stop containers from others
  docker_container:
    name: "{{ item }}"
    state: stopped
  when: "not item | regex_search('.*-(' + deployer_env + '|deployer)')"
  loop: "{{ result.containers | map(attribute='Names') | flatten }}"
  tags: always
