---
- name: Verify the image
  hosts: deployer_instance
  gather_facts: false
  tasks:
    - name: Get docker host info
      docker_host_info:
        verbose_output: yes
        images: yes
      register: result

    - name: Make sure the image exists
      assert:
        that:
          - "(deployer_image_prod_app + ':latest') in images"
      vars:
        images: "{{ result.images | map(attribute='RepoTags') | flatten }}"

    - name: Start a container from this image
      docker_container:
        name: dev-tutorial-app-prod-verify
        image: "{{ deployer_image_prod_app }}"
        etc_hosts:
          dev-tutorial-api-molecule: 127.0.0.1 # NGINX will test proxy hosts at startup
        state: started

    - name: Add container to inventory
      add_host:
        name: dev-tutorial-app-prod-verify
        groups: containers

- name: Verify the container aspect
  hosts: dev-tutorial-app-prod-verify
  gather_facts: false
  tasks:
    - name: Get embedded application stats
      stat:
        path: /usr/share/nginx/dev-tutorial-app
      register: static_app

    - name: Make sure everything is embedded
      assert:
        that:
          - "static_app.stat.exists"
          - "static_app.stat.isdir is defined"
          - "static_app.stat.isdir"

- name: Stop the test container
  hosts: deployer_instance
  no_log: "{{ molecule_no_log }}"
  gather_facts: no
  tasks:
    - name: Stop the test container
      docker_container:
        name: dev-tutorial-app-prod-verify
        state: absent
