---
- name: Verify the image
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get docker host info
      docker_host_info:
        verbose_output: yes
        images: yes
      register: result

    - name: Make sure the image exists
      assert:
        that:
          - "'dev-tutorial-app-prod-molecule:latest' in images"
      vars:
        images: "{{ result.images | map(attribute='RepoTags') | flatten }}"

    - name: Start a container from this image
      docker_container:
        name: dev-tutorial-app-prod-verify
        image: dev-tutorial-app-prod-molecule
        auto_remove: yes
        state: started

    - name: Add container to inventory
      add_host:
        name: dev-tutorial-app-prod-verify
        ansible_connection: docker
        ansible_python_interpreter: /usr/bin/python3

- name: Verify the container aspect
  hosts: dev-tutorial-app-prod-verify
  gather_facts: false
  tasks:
    - name: Get embedded application stats
      stat:
        path: /usr/share/nginx/dev-tutorial-app
      register: static_app

    - name: Make sure the application is embedded
      assert:
        that:
          - "static_app.stat.exists"
          - "static_app.stat.isdir is defined"
          - "static_app.stat.isdir"

- name: Stop the test container
  hosts: localhost
  no_log: "{{ molecule_no_log }}"
  gather_facts: no
  tasks:
    - name: Stop the test container
      docker_container:
        name: dev-tutorial-app-prod-verify
        state: absent
