---
- name: Verify
  hosts: localhost
  pre_tasks:
    - name: Add the future generated container
      add_host:
        name: dev-tutorial-app-molecule
        ansible_connection: docker
        ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Get docker host info
      docker_host_info:
        verbose_output: yes
        containers: yes
        containers_filters:
          status: running
      register: result

    - name: Make sure that application containers are running
      assert:
        that:
          - "'/dev-tutorial-app-molecule' in containers"
      vars:
        containers: "{{ result.containers | map(attribute='Names') | flatten }}"

    - name: Wait for frontend application port
      wait_for:
        port: 4200
        sleep: 5
        timeout: 300
        state: started
      delegate_to: dev-tutorial-app-molecule

    - name: Make sure the app is started
      uri:
        url: "http://localhost:4200"
      delegate_to: dev-tutorial-app-molecule
