---
- name: Converge
  hosts: localhost
  vars:
    deployer_env: molecule
    deployer_host_system: "{{ lookup('env', 'HOST_SYSTEM') }}"
    deployer_local_workspace: "{{ lookup('env', 'WORKSPACE_LOCAL') }}"
    deployer_hosted_workspace: "{{ lookup('env', 'WORKSPACE_HOSTED') }}"
  roles:
    - role: build-tutorials
