---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Remove the containers
      docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - dev-tutorial-api-molecule
        - dev-tutorial-mongo-molecule

- import_playbook: ../../../build-api/molecule/default/cleanup.yml
