---
- name: Prepare
  hosts: instance
  no_log: "{{ molecule_no_log }}"
  roles:
    - role: build-common
      project_paths:
        - "{{ deployer_local_workspace }}/dev-tutorial-api"
    - role: build-api
    - role: run-common
