---
- name: Verify
  hosts: instance
  gather_facts: no
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Get docker host info
      docker_host_info:
        verbose_output: yes
        containers: yes
        containers_filters:
          status: running
      register: result

    - name: Make sure that application containers are running
      assert:
        that:
          - "('/' + deployer_container_api) in containers"
          - "('/' + deployer_container_db) in containers"
      vars:
        containers: "{{ result.containers | map(attribute='Names') | flatten }}"

    - name: Make sure the app starts
      uri:
        url: "http://localhost:3000/api/tuto"
      register: _result
      until: _result.status == 200
      retries: 10
      delay: 5
      delegate_to: "{{ deployer_container_api }}"
