---
- name: Build sources
  include_role:
    name: package-sources
  vars:
    package_sources_directory: /usr/src/app/app-ui
    package_sources_changes: [node_modules, src]
    package_sources_build_command: yarn build
    package_sources_fetch_path: /tmp/app

- name: Build image
  include_tasks: "build_image.yml"
  when: "inventory_hostname in groups['deployer']"
