env:
  node: true
  es2021: true
  mocha: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent: [error, 2]
  linebreak-style: [error, unix]
  quotes: [error, single]
  semi: [error, always]
  eol-last: [error, always]
  no-console: [error, { allow: [warn, error] }]
  no-unused-vars: 0
  space-before-function-paren: [error, never]
  "@typescript-eslint/no-unused-vars": [error]
  "@typescript-eslint/no-explicit-any": 0
