---
extends: default
rules:
  braces:
    forbid: false
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  line-length:
    max: 140
  truthy:
    allowed-values: ["true", "false", "True", "False", "yes", "no"]
    check-keys: true
