---
- name: Pull the production image
  docker_image:
    name: "{{ deploy_api_image }}"
    source: pull

- name: Deploy the production database
  docker_container:
    name: "{{ deploy_api_db_container }}"
    image: mongo
    state: started
    auto_remove: yes
    log_driver: none
    networks:
      - name: "{{ deploy_api_network }}"
    networks_cli_compatible: no

- name: Deploy the production image
  docker_container:
    name: "{{ deploy_api_container }}"
    image: "{{ deploy_api_image }}"
    state: started
    auto_remove: yes
    # command: "sleep infinity"
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - name: "{{ deploy_api_network }}"
    networks_cli_compatible: no
