---
- name: Check for test coverage data
  stat:
    path: dev-tutorial-api/coverage/lcov-report
  register: coverage_data

- name: Missing coverage data
  set_fact:
    docsgen_warnings: "{{ docgen_warnings + [{ generator: 'coverage', warn }] }}"
  vars:
    warn: >
      Tests coverage has not been executed.
      No HTML report will be generated.
      Please run tests first.
      Then regenerate the documentation.
  when: not coverage_data.stat.exists

- name: Generate test coverage HTML report
  copy:
    src: dev-tutorial-api/coverage/lcov-report/
    dest: docs/html/coverage
    remote_src: yes
  when: coverage_data.stat.exists
