---
- name: Generate {{ task_item }} project documentation
  shell:
    chdir: "dev-tutorial-{{ task_item }}"
    cmd: >
      typedoc
      --out ../docs/html/tsdoc-{{ task_item }}
      --name 'Dev'' Tutorial {{ task_item | upper }} Project'
      --exclude '**/*.spec.ts' --exclude '**/@types/**' --exclude '**/*e2e**'
      --excludeExternals
      --hideGenerator
      --readme none
      src
    # creates: "../docs/html/tsdoc-{{ task_item }}"
