---
- name: Remove generated files
  file:
    path: "{{ deployer_local_workspace }}/dev-tutorial-api/Dockerfile"
    state: absent

- name: Remove the local image
  docker_image:
    name: "{{ build_api_image }}"
    state: absent
    force_absent: yes
