---
- name: Get last build date
  shell: echo "$(($(date +%s) - $(stat -c %Y /usr/src/app/api/dist/index.js || echo 0)))"
  register: dist_date
  changed_when: False

- name: Detect source changes
  find:
    paths: /usr/src/app/api
    recurse: yes
    age: "-{{ dist_date.stdout }}s"
    file_type: file
  register: src_changes

- name: Build the production directory
  command:
    cmd: yarn tsc
    chdir: /usr/src/app/api
  when: "src_changes.matched > 0"

- name: Fetch the package
  synchronize:
    src: /usr/src/app/api/dist
    dest: /tmp/api
    mode: pull
