---
- name: Build sources
  include_role:
    name: package-sources
  vars:
    package_sources_directory: /usr/src/app/api
    package_sources_changes: [node_modules, public, src, tutorials]
    package_sources_build_command: yarn tsc
    package_sources_fetch_path: /tmp/api

- name: Build image
  include_tasks: "build_image.yml"
  when: "inventory_hostname in groups['deployer']"
