---
- name: Generate environment files
  template:
    src: environments/environment.api.ts.j2
    dest: "{{ deployer_local_workspace }}/dev-tutorial-api/src/environments/environment.ts"
  loop:

- name: Generate frontend environment file
  template:
    src: environments/environment.app.ts.j2
    dest: "{{ deployer_local_workspace }}/dev-tutorial-app/src/environments/environment.ts"
