---
# Ansible
ansible_connection: local

# Deployer
deployer_host_system: "{{ lookup('env', 'HOST_SYSTEM') }}"
deployer_local_workspace: "{{ lookup('env', 'WORKSPACE_LOCAL') }}"
deployer_hosted_workspace: "{{ lookup('env', 'WORKSPACE_HOSTED') }}"

# Images
deployer_image_api: dev-tutorial-api
deployer_image_app: dev-tutorial-app
deployer_image_prod_api: tzimy/dev-tutorial-api-prod
deployer_image_prod_app: tzimy/dev-tutorial-app-prod

# Containers Networks
deployer_network_db: dev-tutorial-network-db
deployer_network_api: dev-tutorial-network-api

# Containers
deployer_container_api: dev-tutorial-api
deployer_container_app: dev-tutorial-app
deployer_container_prod_api: dev-tutorial-back
deployer_container_prod_app: dev-tutorial-front
