---
- name: Create
  hosts: deployer_instance
  no_log: "{{ molecule_no_log }}"
  vars:
    deployer_container_api: instance
  roles:
    - role: build-common
      project_paths:
        - "{{ deployer_local_workspace }}/dev-tutorial-api"
    - role: build-api
    - role: run-common
    - role: run-api
      run_api_command: sleep infinity
