all:    
  children:
    deployer:
      hosts:
        dev-tutorial-deployer:
    containers:
      children:
        deployer:
      hosts:
        dev-tutorial-front:
        dev-tutorial-app:
        dev-tutorial-api:
        dev-tutorial-mongo-dev:
        dev-tutorial-mongo-test:
        dev-tutorial-mongo-ci:
        dev-tutorial-mongo-prod:
        dev-tutorial-docs:
        dev-tutorial-docsgen:
        