all:
  hosts:
    dev:
      ansible_connection: local
      deployer_host: 'host.docker.internal'
      deployer_host_system: "{{ lookup('env', 'HOST_SYSTEM') }}"
      deployer_local_workspace: "{{ lookup('env', 'WORKSPACE_LOCAL') }}"
      deployer_hosted_workspace: "{{ lookup('env', 'WORKSPACE_HOSTED') }}"
      prepare_env_api_production: no
      prepare_env_api_docker: { host: 'host.docker.internal', port: 2375 }
      prepare_env_container_env_backend:
        DEBUG: "app:server,app:access,app:socket"

    test:
      ansible_connection: local
      deployer_host: 'host.docker.internal'
      deployer_host_system: "{{ lookup('env', 'HOST_SYSTEM') }}"
      deployer_local_workspace: "{{ lookup('env', 'WORKSPACE_LOCAL') }}"
      deployer_hosted_workspace: "{{ lookup('env', 'WORKSPACE_HOSTED') }}"
      prepare_env_backend_command: yarn test
      prepare_env_frontend_command: yarn test
      prepare_env_wait_for_init: no
      prepare_env_api_volumes: []
      prepare_env_api_production: no
      prepare_env_api_docker: { host: 'host.docker.internal', port: 2375 }
      prepare_env_container_env_backend:
        DEBUG: "app:access,app:docker,test:*"
        DEV_API_EXTRA_TUTORIALS: "test/extra-tuto test/extra-tuto2"
        CHOMA_SEED: ""

    ci:
      ansible_connection: local
      deployer_host: 'host.docker.internal'
      deployer_host_system: "{{ lookup('env', 'HOST_SYSTEM') }}"
      deployer_local_workspace: "{{ lookup('env', 'WORKSPACE_LOCAL') }}"
      deployer_hosted_workspace: "{{ lookup('env', 'WORKSPACE_HOSTED') }}"
      prepare_env_backend_command: yarn test-ci
      prepare_env_frontend_command: yarn test-ci
      #prepare_env_force: yes
      prepare_env_api_production: no
      prepare_env_api_docker: 
        socketPath: '/var/run/docker.sock'
