all:
  hosts:
    deployer:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      deployer_host_system: "{{ lookup('env', 'HOST_SYSTEM') }}"
      deployer_local_workspace: "{{ lookup('env', 'WORKSPACE_LOCAL') }}"
      deployer_hosted_workspace: "{{ lookup('env', 'WORKSPACE_HOSTED') }}"
      dockerize_api_production: no
    dev-tutorial-api:
      ansible_connection: docker
      ansible_python_interpreter: /usr/bin/python3
    dev-tutorial-app:
      ansible_connection: docker
      ansible_python_interpreter: /usr/bin/python3
    dev-tutorial-docsgen:
      ansible_connection: docker
      ansible_python_interpreter: /usr/bin/python3
