all:
  children:
    frontend:
  hosts:
    # Local node, the deployer itself
    deployer:
    # The API service (dev)
    dev-tutorial-api:
      ansible_connection: docker
      ansible_python_interpreter: /usr/bin/python3
    dev-tutorial-app:
      ansible_connection: docker
      ansible_python_interpreter: /usr/bin/python3
