all:
  hosts:
    dev-tutorial-deployer:
      deployer_env: prod
      run_api_token_access_secret: lagv9f6whb4yd6oiyqxxabb2f4u0prw0
      run_api_token_refresh_secret: zsoxh0mdmygu7q1nt2sls4p7u7t5kq0h
      run_api_command: sleep infinity
      run_app_command: sleep infinity
  children:
    backends:
      hosts:
        dev-tutorial-back:
          api_port: 3000
          socket_port: 3001
    frontends:
      hosts:
        dev-tutorial-front:
          app_port: 80
    nginx:
      hosts:
        dev-tutorial-front:
