name: Bundle scripts # for an environment without python

on:
  workflow_dispatch:

jobs:
  bundle:
    name: Package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            artifact: dist/compose.exe
          - os: ubuntu-latest
            artifact: dist/compose
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install pyinstaller
      - run: pyinstaller bin/compose/compose.py -y --onefile
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.artifact }}
