name: Compose bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bundle:
    name: Windows bundle
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get required dependencies
        run: pip install pyinstaller
      - name: Compose bundle
        run: pyinstaller compose.py -y --onefile
