name: Compose bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bundle:
    name: Package
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - run: pip install pyinstaller
      - run: pyinstaller compose.py -y --onefile
