name: Compose bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bundle:
    name: Package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install pyinstaller
      - run: pyinstaller compose.py -y --onefile
      - run: ls dist
