name: Compose bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bundle:
    name: Windows bundle
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: python --version
