name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_HOST: tcp://0.0.0.0:2375
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: ./compose.py -e ci --build
    - name: Run the API Tests
      run: ./compose.py -e ci --up -s api
