name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint
      uses: reviewdog/action-eslint@v1.0.0
    - name: Build test images
      run: ./compose.py -e ci --build
    - name: Run tests
      run: ./compose.py -e ci --up -s api
