name: Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run tests
        run: ./bin/compose/compose.py dockerize ci -v
      - name: Publish Test Report
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "**/report/TESTS-*.xml"
