name: Tests

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ln -s .github/linters/.eslintrc.yml .eslintrc.yml
      - uses: nvuillam/mega-linter@v4
  test:
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run tests
        run: ./compose.py dockerize ci -s api
      - run: find . -name '*.xml'
      - run: find . -name '*report*'
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: '**/test-results.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
