name: Tests

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm install eslint-config-eslint 
      - uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*/.*.j2
          ANSIBLE_DIRECTORY: ./dev-tutorial-deployer
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
  test:
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run tests
        run: ./compose.py dockerize ci -s api
      - run: ./compose.py dockerize ci -s api
      - name: ls *.xml
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: '**/test-results.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
