name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm install eslint-config-eslint 
      - uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          LINTER_RULES_PATH: ./dev-tutorial-api
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.yml
          VALIDATE_TYPESCRIPT_ES: true
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build test images
        run: ./compose.py -e ci --build
      - name: Run tests
        run: ./compose.py -e ci --up -s api
