name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - run: yarn global add eslint
      - uses: actions/checkout@v2
      - name: eslint
        uses: reviewdog/action-eslint@v1
        #with:
        #  reporter: github-pr-review # Change reporter.
        #  eslint_flags: 'src/'
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: reviewdog/action-eslint@v1.0.0
      - name: Build test images
        run: ./compose.py -e ci --build
      - name: Run tests
        run: ./compose.py -e ci --up -s api
