---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Destroy images
      docker_image:
        name: dev-tutorial-app-molecule
        state: absent
