---
- name: Verify
  hosts: instance
  no_log: "{{ molecule_no_log }}"
  gather_facts: no
  tasks:
    - name: Get docker host info
      docker_host_info:
        verbose_output: yes
        images: yes
      register: result

    - name: Make sure that the image exist
      assert:
        that:
          - "(deployer_image_app + ':latest') in images"
      vars:
        images: "{{ result.images | map(attribute='RepoTags') | flatten }}"
